@echo off
echo Installing dependencies...
pip install -r requirements.txt
echo Initializing database...
python init_local_db.py
echo Starting server...
uvicorn app.main:app --reload --port 8001
pause
